app = "short-form-video-accelerator"
primary_region = "iad"
kill_timeout = 60

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8000"
  DEBUG = "False"
  LOG_LEVEL = "INFO"
  AWS_REGION = "us-west-2"
  S3_BUCKET_NAME = "digital-frontier-assets"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["frontend"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  processes = ["frontend"]

[processes]
  app = "cd backend && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
  frontend = "cd frontend && nginx -g 'daemon off;'"
