[phases.setup]
nixPkgs = ["python311", "nodejs", "nginx"]

[phases.backend]
cmds = [
  "cd backend && pip install poetry && poetry config virtualenvs.in-project true && poetry install --no-dev"
]

[phases.frontend]
cmds = [
  "cd frontend && npm install && npm run build"
]

[start]
cmd = "cd backend && poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
