name: short-form-video-accelerator-backend
services:
  - name: api
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      repo: the1carver/short-form-video-accelerator
      branch: main
      deploy_on_push: true
    http_port: 8000
    instance_size_slug: basic-xs
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_REGION
        scope: RUN_TIME
        value: us-west-2
      - key: S3_BUCKET_NAME
        scope: RUN_TIME
        value: digital-frontier-assets
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO
    routes:
      - path: /api
        preserve_path_prefix: true
