name: video-accelerator
services:
  - name: backend
    git:
      repo_clone_url: https://github.com/the1carver/short-form-video-accelerator.git
      branch: main
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    http_port: 8000
    instance_size_slug: basic-xs
    envs:
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_ACCESS_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: AWS_SECRET_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AWS_REGION
        scope: RUN_TIME
        value: us-west-2
      - key: S3_BUCKET_NAME
        scope: RUN_TIME
        value: digital-frontier-assets
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      - key: LOG_LEVEL
        scope: RUN_TIME
        value: INFO
    routes:
      - path: /api
        preserve_path_prefix: true

  - name: frontend
    git:
      repo_clone_url: https://github.com/the1carver/short-form-video-accelerator.git
      branch: main
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    http_port: 80
    instance_size_slug: basic-xs
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${APP_URL}
      - key: VITE_FIREBASE_API_KEY
        scope: BUILD_TIME
        type: SECRET
    routes:
      - path: /
