apiVersion: apps/v1
kind: Deployment
metadata:
  name: short-form-video-accelerator-frontend
  labels:
    app: short-form-video-accelerator-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: short-form-video-accelerator-frontend
  template:
    metadata:
      labels:
        app: short-form-video-accelerator-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-files
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: frontend-files
        configMap:
          name: short-form-video-accelerator-frontend-files
      - name: nginx-config
        configMap:
          name: short-form-video-accelerator-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: short-form-video-accelerator-frontend
spec:
  selector:
    app: short-form-video-accelerator-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
